---
organisation: moengage # YOUR GITHUB organisation name
tokens:
  github: '' #YOUR local alice's GITHUB TOKEN
  slack: '' #YOUR local alice's slack TOKEN
  jenkins: '' #YOUR jekin's alice's jenkins TOKEN
repo: #Repo wise settings
  MoEngage:  #YOUR repo name
    checks: # enable these checks, if given none: will trigger all the checks
    - close_dangerous_pr
    - tech_review
    - product_review
    - comment_guidelines
    - notify_lead_on_given_action
    - notify_channel_on_merge
    - notify_on_sensitive_files_touched
    - notify_qa_sign_off
    - remind_direct_release_guideline_on_merge
    sensitive_branches: #the branches you want to prevent
    - dev
    - qa
    - master
    sensitive_files: #the files you want to protect
    - moengage_pull_production_latest
    - moengage_production
    sensitive_file_pattern: '' #sensitive files are inside some directory or starts with some pattern
    product_team: "@riteshg @nalin" # the slack names space separated
    product_plus_required_dir_pattern: 'dashboard' #directory path for which product review is a must
    cc_members: "@satya @pooja" #the slack memeber names space separated
    code_channel: "#code-merged" #the slack channel names in which merged pull request info shoudl be notified
    alert_channel: "#weekly-releases" #the slack channel name in which alerts should be posted
    dev_ops_team: "@pruthvi @adithya" #the slack channel names of your dev ops team
    notify_direct: # settings for direct message on slack
      person_to_be_notified: "@yashwanth" #1 person for any activity notify this person, generally the lead for this repo
      action_to_be_notified_on: 'opened' #1 github action Ex. ["opened", "repoened", "merged"]
      branch_list_to_be_notified: #direct notification on these branches for action set above
      - dev
      - qa
      tech_leads_to_be_notified_on_release_freeze:
      - "@yashwanth"
      - "@pooja"
      - "@satya"
      - "@naveenkumarkokku"
      - "@pruthvi"
      - "@nishant"
      - "@shubhanshu"
      - "@sarang"
      - "@geetima"
      - "@vandana"
      - "@sneh"
    main_branch: 'master' # release branch, generally its master
    test_branch: 'qa' # test branch on which qa is locked to do release testing
    whitelisted_git_members: #NO alerts for these git members only
    - shahp00ja
    - satyamoengage
    - snehsagar
    - vandanamoriwal
    - geetima12
    super_git_members: #GITHUB NAMES for white listing some users to break the rules in a tough case
    - shahp00ja
    - satyamoengage
  segmentation: # REPO 2
    sensitive_branches:
    - develop
    - release
    - qa
    - master
    cc_members: "@akshay @pooja"
    code_channel: "#segmentation-code"
    alert_channel: "#weekly-releases"
    product_team: "@riteshg @nalin"
    dev_ops_team: "@pruthvi @adithya"
    whitelisted_git_members:
    - akgoel-mo
    - shahp00ja
  commons:
    sensitive_branches:
    - develop
    - release
    - qa
    - master
    cc_members: "@akshay @mshekher @pooja"
    code_channel: "#commons-code"
    alert_channel: "#weekly-releases"
    product_team: "@riteshg @nalin"
    dev_ops_team: "@pruthvi @adithya"
    lead_to_be_notified: "@yashwanth"
    whitelisted_git_members:
    - akgoel-mo
    - shahp00ja
    - pruthvintss
dev_ops_team: "@pruthvi @adithya"
JENKINS_BASE: http://ci.moengage.com/
repo_list:
- MoEngage
- MoeDataScience
- mongoengine
- inapp-rest-service
- mongo
- segmentation
- commons
- moengcache
- MoeAbTesting
- apns_client
- Bugsy_Backend
- product-management
- product-recommendation
debug: true
debug_alice:
  sensitive_branches: []
  debug_channel: "#tmp"
  debug_folks: "@pooja"
  whitelisted_git_members:
  - shahp00ja
user_map:
  shahp00ja: pooja
  abhi9moe: abhinav
  moarnab: arnab
  geetima12: geetima
  naveenkumarkokku: naveenkumarkokku
release_notes_link: https://docs.google.com/a/moengage.com/spreadsheets/d/1eW3y-GxGzu8Jde8z4EYC6fRh1Ve4TpbW5qv2-iWs1ks/edit?usp=sharing
